import type { DisclosureStatement } from '@/types'

export async function generateDisclosure(
  content: string,
  style: 'blog' | 'academic' | 'marketing' = 'blog'
): Promise<DisclosureStatement> {
  // Analyze content to determine appropriate disclosure
  const contentAnalysis = analyzeContentForDisclosure(content)
  
  let statement = ''
  let placement: 'beginning' | 'end' | 'both' = 'beginning'
  const alternatives: string[] = []
  
  switch (style) {
    case 'blog':
      if (contentAnalysis.hasAIContent) {
        statement = 'This content was created with the assistance of artificial intelligence tools. All information has been reviewed and verified for accuracy.'
        alternatives.push(
          'AI tools were used to help research and draft portions of this content.',
          'This post was written with AI assistance to enhance clarity and completeness.',
          'Some sections of this content were generated using AI technology and have been fact-checked by our team.'
        )
      } else {
        statement = 'This content was created entirely by human authors without AI assistance.'
        alternatives.push(
          'This post represents original human-authored content.',
          'No artificial intelligence was used in creating this content.'
        )
      }
      placement = 'end'
      break
      
    case 'academic':
      if (contentAnalysis.hasAIContent) {
        statement = 'Disclosure: Artificial intelligence tools were utilized in the preparation of this work for research assistance and content organization. All conclusions and interpretations remain the responsibility of the authors.'
        alternatives.push(
          'AI Assistance Declaration: This research utilized artificial intelligence for data analysis and content structuring while maintaining human oversight for all conclusions.',
          'Technology Disclosure: AI tools were employed for literature review and initial drafting, with all content subsequently reviewed and validated by qualified researchers.'
        )
      } else {
        statement = 'This work was conducted and authored entirely without the use of artificial intelligence tools.'
        alternatives.push(
          'No AI Declaration: This research was completed using traditional methodologies without artificial intelligence assistance.'
        )
      }
      placement = 'beginning'
      break
      
    case 'marketing':
      if (contentAnalysis.hasAIContent) {
        statement = 'This content was developed using AI technology to ensure comprehensive coverage of topics relevant to our audience. All claims and recommendations have been verified by our team.'
        alternatives.push(
          'We use cutting-edge AI tools to help create informative content while maintaining our commitment to accuracy.',
          'This material was crafted with AI assistance to provide you with the most current and relevant information.',
          'Our team leverages AI technology to enhance content quality while ensuring all information meets our standards.'
        )
      } else {
        statement = 'This content represents our team\'s original insights and expertise, created without AI assistance.'
        alternatives.push(
          'This content showcases our team\'s authentic expertise and original thinking.',
          'Our human experts crafted this content based on their direct experience and knowledge.'
        )
      }
      placement = 'end'
      break
  }
  
  return {
    statement,
    style,
    placement,
    alternatives
  }
}

function analyzeContentForDisclosure(content: string) {
  // Simple heuristics to determine if content might be AI-generated
  const aiIndicators = [
    'as an ai', 'i\'m an ai', 'artificial intelligence',
    'generated by ai', 'ai-generated', 'machine learning',
    'neural network', 'algorithm', 'automated'
  ]
  
  const structuralIndicators = [
    // Very structured content
    /^\d+\./gm, // Numbered lists
    /^[•\-\*]/gm, // Bullet points
    /in conclusion/i,
    /to summarize/i,
    /furthermore/i,
    /moreover/i
  ]
  
  const hasAIKeywords = aiIndicators.some(indicator => 
    content.toLowerCase().includes(indicator)
  )
  
  const structuralScore = structuralIndicators.reduce((score, pattern) => {
    const matches = content.match(pattern)
    return score + (matches ? matches.length : 0)
  }, 0)
  
  // If content is very structured or mentions AI, assume AI assistance
  const hasAIContent = hasAIKeywords || structuralScore > 5
  
  return {
    hasAIContent,
    structuralScore,
    hasAIKeywords
  }
}